name = "shikaku-minder"
compatibility_date = "2024-09-23"

[assets]
directory = "./out"

[[routes]]
pattern = "shikaku-minder.com/*"
custom_domain = true

[[routes]]
pattern = "www.shikaku-minder.com/*"
custom_domain = true
